In [2]:
sam1=SAM()
sam1.load_data('../../Active_SAM_joined/SAM_XT_joined_Slc17a6_cleaned_03122205.h5ad')

In [1]:
!pip install anndata==0.8.0

Requirement already satisfied: anndata==0.8.0 in /scratch/miniconda/lib/python3.7/site-packages (0.8.0)
Requirement already satisfied: pandas>=1.1.1 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.3.5)
Requirement already satisfied: typing_extensions in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (4.2.0)
Requirement already satisfied: importlib_metadata>=0.7 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (4.11.4)
Requirement already satisfied: h5py>=3 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (3.8.0)
Requirement already satisfied: packaging>=20 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (21.3)
Requirement already satisfied: natsort in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (8.1.0)
Requirement already satisfied: scipy>1.4 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.7.3)
Requirement already satisfied: numpy>=1.16.5 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.21.6)
Requirement already satisfied: zipp>=0.5 in /scratch/miniconda/lib/python3.7/site-packages (from importlib_metadata>=0.7->anndata==0.8.0) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /scratch/miniconda/lib/python3.7/site-packages (from packaging>=20->anndata==0.8.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /scratch/miniconda/lib/python3.7/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /scratch/miniconda/lib/python3.7/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2022.1)
Requirement already satisfied: six>=1.5 in /scratch/miniconda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.1->anndata==0.8.0) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [3]:
!pip install loompy

Requirement already satisfied: loompy in /scratch/miniconda/lib/python3.7/site-packages (3.0.8)
Requirement already satisfied: setuptools in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (62.6.0)
Requirement already satisfied: numpy in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (1.21.6)
Requirement already satisfied: click in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (8.1.8)
Requirement already satisfied: scipy in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (1.7.3)
Requirement already satisfied: numpy-groupies in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (0.9.22)
Requirement already satisfied: h5py in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (3.8.0)
Requirement already satisfied: numba in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (0.52.0)
Requirement already satisfied: importlib-metadata in /scratch/miniconda/lib/python3.7/site-packages (from click->loompy) (4.11.4)
Requirement already satisfied: llvmlite<0.36,>=0.35.0 in /scratch/miniconda/lib/python3.7/site-packages (from numba->loompy) (0.35.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /scratch/miniconda/lib/python3.7/site-packages (from importlib-metadata->click->loompy) (4.2.0)
Requirement already satisfied: zipp>=0.5 in /scratch/miniconda/lib/python3.7/site-packages (from importlib-metadata->click->loompy) (3.8.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [1]:
from samalg import SAM
import scanpy as sc
import statistics
import matplotlib.pyplot as plt
import seaborn as sns
import random
import pandas as pd
import matplotlib.colors
import scipy
import numpy as np
import sklearn.metrics as metrics
from scipy import sparse
from samap.mapping import SAMAP
from samap.analysis import (get_mapping_scores, GenePairFinder, transfer_annotations,
                            sankey_plot, chord_plot, CellTypeTriangles, 
                            ParalogSubstitutions, FunctionalEnrichment,
                            convert_eggnog_to_homologs, GeneTriangles)
from samalg import SAM
import pandas as pd
from Bio import SeqIO
from samap.utils import (save_samap, load_samap)
import scanpy as sc
import loompy

In [4]:
sam1.adata.obs

,n_genes,n_counts,key,leiden_clusters,subclass_id_label_mapping,subclass_id_label_lc,subclass_id_label_mapping_nounlabeled,subclass_id_label_crossed,subclass_id_label_crossed_nn
AAACCCACAAGCGGAT Run 18 sample 2,2143,4321.0,Run 18 sample 2,51,094 SCH Six6 Cdc14a Gaba,17,094 SCH Six6 Cdc14a Gaba,094 SCH Six6 Cdc14a Gaba,094 SCH Six6 Cdc14a Gaba
AAACCCACAGTCTTCC Run 18 sample 2,2944,6202.0,Run 18 sample 2,20,Unlabeled,63,ri_12,ri_12,ri_12
AAACCCACATAGACTC Run 18 sample 2,2207,5645.0,Run 18 sample 2,18,Unlabeled,174,ri_13,115 MS-SF Bsx Glut,115 MS-SF Bsx Glut
AAACCCAGTCCCTGTT Run 18 sample 2,2508,5343.0,Run 18 sample 2,45,Unlabeled,42,ri_4,ri_4,ri_4
AAACCCAGTCTGTAAC Run 18 sample 2,3797,10901.0,Run 18 sample 2,34,097 PVHd-SBPV Six3 Prox1 Gaba,85,097 PVHd-SBPV Six3 Prox1 Gaba,097 PVHd-SBPV Six3 Prox1 Gaba,097 PVHd-SBPV Six3 Prox1 Gaba
...,...,...,...,...,...,...,...,...,...
TTTGTTGAGTCGAGGT Run 18 sample 10,2721,5535.0,Run 18 sample 10,62,Unlabeled,32,ri_31,082 CEA-BST Ebf1 Pdyn Gaba,082 CEA-BST Ebf1 Pdyn Gaba
TTTGTTGCAGAACCGA Run 18 sample 10,1831,3386.0,Run 18 sample 10,2,Unlabeled,5,ri_1,ri_1,ri_1
TTTGTTGCAGCGGATA Run 18 sample 10,1830,2999.0,Run 18 sample 10,25,106 PVpo-VMPO-MPN Hmx2 Gaba,182,106 PVpo-VMPO-MPN Hmx2 Gaba,106 PVpo-VMPO-MPN Hmx2 Gaba,106 PVpo-VMPO-MPN Hmx2 Gaba
TTTGTTGCAGTTGTTG Run 18 sample 10,1886,3122.0,Run 18 sample 10,50,106 PVpo-VMPO-MPN Hmx2 Gaba,59,106 PVpo-VMPO-MPN Hmx2 Gaba,106 PVpo-VMPO-MPN Hmx2 Gaba,106 PVpo-VMPO-MPN Hmx2 Gaba
TTTGTTGGTCACTCTC Run 18 sample 10,3888,11166.0,Run 18 sample 10,124,Unlabeled,225,ri_48,ri_48,ri_48

In [3]:
sam1.adata.obs = sam1.adata.obs.loc[:,['key','n_genes','n_counts','subclass_id_label_lc']]

In [6]:
sam1.adata.obs

,key,n_genes,n_counts,subclass_id_label_lc
AAACCCACAAGCGGAT Run 18 sample 2,Run 18 sample 2,2143,4321.0,17
AAACCCACAGTCTTCC Run 18 sample 2,Run 18 sample 2,2944,6202.0,63
AAACCCACATAGACTC Run 18 sample 2,Run 18 sample 2,2207,5645.0,174
AAACCCAGTCCCTGTT Run 18 sample 2,Run 18 sample 2,2508,5343.0,42
AAACCCAGTCTGTAAC Run 18 sample 2,Run 18 sample 2,3797,10901.0,85
...,...,...,...,...
TTTGTTGAGTCGAGGT Run 18 sample 10,Run 18 sample 10,2721,5535.0,32
TTTGTTGCAGAACCGA Run 18 sample 10,Run 18 sample 10,1831,3386.0,5
TTTGTTGCAGCGGATA Run 18 sample 10,Run 18 sample 10,1830,2999.0,182
TTTGTTGCAGTTGTTG Run 18 sample 10,Run 18 sample 10,1886,3122.0,59
TTTGTTGGTCACTCTC Run 18 sample 10,Run 18 sample 10,3888,11166.0,225

In [4]:
for i in range(0,30):
    dat = sc.read_loom('subset_Allen_institute_Full_subclass_test_250_'+str(i)+'.loom')
    dat.obs_names = dat.obs['obs_names']
    dat.var_names = list(dat.var['x'])
    
    sam=SAM(dat)
    sam.preprocess_data()
    sam.run()
    
    sam.adata.obs_names_make_unique()
    sam.adata.var_names_make_unique()

    sam1.adata.obs_names_make_unique()
    sam1.adata.var_names_make_unique()
    
    sams = {'mg':sam,'xt':sam1}

    sm = SAMAP(
        sams,
        f_maps = 'BLASTMAPPING/maps/active_maps/',
    )
    
    sm.run(pairwise=True)
    
    save_samap(sm , 'sm_Allen_Full_xt_slc17a6_cleaned_03122025_subclass_250_'+str(i)+'.pkl')

/scratch/miniconda/lib/python3.7/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

RUNNING SAM
Iteration: 0, Convergence: 1.0
Iteration: 1, Convergence: 0.8149377023101017
Computing the UMAP embedding...
Elapsed time: 296.9610140323639 seconds
Not updating the manifold...
Not updating the manifold...
19358 `mg` gene symbols match between the datasets and the BLAST graph.
19564 `ri` gene symbols match between the datasets and the BLAST graph.
Prepping datasets for translation.
Translating feature spaces pairwise.
Projecting data into joint latent space. 230.61634588241577
Correcting data with means. 273.8510842323303
Expanding neighbourhoods of species mg...
Expanding neighbourhoods of species ri...
Indegree coarsening
0/8 (0, 145129)
1/8 (20000, 145129)
2/8 (40000, 145129)
3/8 (60000, 145129)
4/8 (80000, 145129)
5/8 (100000, 145129)
6/8 (120000, 145129)
7/8 (140000, 145129)
Rescaling edge weights by expression correlations.
Concatenating SAM objects...
ITERATION: 0
Average alignment score (A.S.):  0.4648191835190593
Max A.S. improvement: 0.9745718164709214
Min A.S. improvement: 0.0
Calculating gene-gene correlations in the homology graph...
Prepping datasets for translation.
Translating feature spaces pairwise.
Projecting data into joint latent space. 155.5289273262024
Correcting data with means. 211.6886224746704
Expanding neighbourhoods of species mg...
Expanding neighbourhoods of species ri...
Indegree coarsening
0/8 (0, 145129)
1/8 (20000, 145129)
2/8 (40000, 145129)
3/8 (60000, 145129)
4/8 (80000, 145129)
5/8 (100000, 145129)
6/8 (120000, 145129)
7/8 (140000, 145129)
Rescaling edge weights by expression correlations.
Concatenating SAM objects...
ITERATION: 1
Average alignment score (A.S.):  0.5182023890015053
Max A.S. improvement: 0.30732790953199285
Min A.S. improvement: -0.28234554299569925
Calculating gene-gene correlations in the homology graph...
Prepping datasets for translation.
Translating feature spaces pairwise.
Projecting data into joint latent space. 153.84684300422668
Correcting data with means. 230.28540444374084
Expanding neighbourhoods of species mg...
Expanding neighbourhoods of species ri...
Indegree coarsening
0/8 (0, 145129)
1/8 (20000, 145129)
2/8 (40000, 145129)
3/8 (60000, 145129)
4/8 (80000, 145129)
5/8 (100000, 145129)
6/8 (120000, 145129)
7/8 (140000, 145129)
Rescaling edge weights by expression correlations.
Concatenating SAM objects...
ITERATION: 2
Average alignment score (A.S.):  0.5236406838051222
Max A.S. improvement: 0.10149512673031588
Min A.S. improvement: -0.05512340686107495
Alignment score --- 0.5236406838051222
Running UMAP on the stitched manifolds.
Elapsed time: 55.409803990523024 minutes.