In [1]:
!pip install anndata==0.8.0

Requirement already satisfied: anndata==0.8.0 in /scratch/miniconda/lib/python3.7/site-packages (0.8.0)
Requirement already satisfied: scipy>1.4 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.7.3)
Requirement already satisfied: numpy>=1.16.5 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.21.6)
Requirement already satisfied: pandas>=1.1.1 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.3.5)
Requirement already satisfied: natsort in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (8.1.0)
Requirement already satisfied: typing_extensions in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (4.2.0)
Requirement already satisfied: packaging>=20 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (21.3)
Requirement already satisfied: importlib_metadata>=0.7 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (4.11.4)
Requirement already satisfied: h5py>=3 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (3.8.0)
Requirement already satisfied: zipp>=0.5 in /scratch/miniconda/lib/python3.7/site-packages (from importlib_metadata>=0.7->anndata==0.8.0) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /scratch/miniconda/lib/python3.7/site-packages (from packaging>=20->anndata==0.8.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /scratch/miniconda/lib/python3.7/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /scratch/miniconda/lib/python3.7/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2022.1)
Requirement already satisfied: six>=1.5 in /scratch/miniconda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.1->anndata==0.8.0) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [35]:
from samap.mapping import SAMAP
from samap.analysis import (get_mapping_scores, GenePairFinder, transfer_annotations,
                            sankey_plot, chord_plot, CellTypeTriangles, 
                            ParalogSubstitutions, FunctionalEnrichment,
                            convert_eggnog_to_homologs, GeneTriangles)
from samalg import SAM
import pandas as pd
from Bio import SeqIO
from samap.utils import (save_samap, load_samap)
import scanpy as sc
import matplotlib.colors
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from scipy import sparse 
from scipy import cluster
import seaborn as sns
import random
import sklearn
from sklearn.neighbors import KernelDensity
import time
import dill
import pickle
from scipy.spatial import distance
import os
import scipy

In [36]:
with open('../../parent_dict_v2.pkl', 'rb') as f:
    parent_dict = pickle.load(f)

In [37]:
fn = '../../Active_SAM_joined/SAM_MO_soupx_plus5_cleaned_03122025.h5ad'

In [38]:
sam = SAM()
sam.load_data(fn)

In [80]:
lsaturn_m = pd.read_csv('../../SATURN_hypo_september2026_mapping_30_seeds/MO_30_seeds.csv', index_col = 'barcode')

In [81]:
meta_folder = '../../Active_SAMap_Joined/MO_metadata/'

In [82]:
mn = os.listdir('../../Active_SAMap_Joined/MO_metadata/')

In [83]:
pd.read_csv(meta_folder + mn[3])

,Unnamed: 0,orig.ident,nCount_RNA,nFeature_RNA,n_counts,n_genes,key,eq_subclass_nounlabeled,leiden_removal,SCT_snn_res.5,leiden_clusters,subclass_id_label_mapping,subclass_id_label_lc
0,AAACCCATCTCAAAGC,MO,11772.0,3844,11772.0,3844,Run12_sample1,mo_9,35,15,86,Unlabeled,86
1,AAACGAACAGCACGAA,MO,4877.0,2561,4877.0,2561,Run12_sample1,mo_5,39,105,240,Unlabeled,240
2,AAACGAAGTCGGCACT,MO,5221.0,2859,5221.0,2859,Run12_sample1,108 ARH-PVp Tbx3 Gaba,35,14,16,108 ARH-PVp Tbx3 Gaba,16
3,AAACGAATCCACCCTA,MO,7922.0,3360,7922.0,3360,Run12_sample1,mo_2,78,87,527,Unlabeled,527
4,AAACGAATCCCAGCGA,MO,7020.0,3204,7020.0,3204,Run12_sample1,128 VMH Fezf1 Glut,2,16,333,128 VMH Fezf1 Glut,333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75325,TTTGTTGGTACTAACC,MO,5496.0,2569,5496.0,2569,Run12_sample12,057 NDB-SI-MA-STRv Lhx8 Gaba,8,26,156,057 NDB-SI-MA-STRv Lhx8 Gaba,156
75326,TTTGTTGGTCACAATC-1,MO,2974.0,1804,2974.0,1804,Run12_sample12,089 PVR Six3 Sox3 Gaba,11,52,119,089 PVR Six3 Sox3 Gaba,119
75327,TTTGTTGTCCAACCAA,MO,5601.0,2608,5601.0,2608,Run12_sample12,mo_9,5,56,265,Unlabeled,265
75328,TTTGTTGTCCCTGTTG,MO,6209.0,2759,6209.0,2759,Run12_sample12,mo_3,1,33,522,Unlabeled,522
75329,TTTGTTGTCGCAGTTA,MO,5151.0,2617,5151.0,2617,Run12_sample12,086 MPO-ADP Lhx8 Gaba,36,68,69,086 MPO-ADP Lhx8 Gaba,69

In [84]:
test = pd.read_csv(meta_folder + mn[0])['subclass_id_label_mapping']

In [85]:
barcodes = pd.read_csv(meta_folder + mn[0])['Unnamed: 0']

In [86]:
raw_lc = pd.read_csv(meta_folder + mn[0])['subclass_id_label_lc']

In [87]:
df_lc = pd.DataFrame(data = list(raw_lc), index = list(barcodes), columns = ['raw_lc'])

In [88]:
mode_df = pd.DataFrame(index = [a for a in range(len(test))], columns = [b for b in range(len(mn))])
for j in range(len(mn)):
    print(mn[j])
    dat = list(pd.read_csv(meta_folder + mn[j])['subclass_id_label_lc'])
    mode_df.loc[:,j] = dat

MO_metadata_soupxplus5_cleaned_03122025_subclass_250_22.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_8.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_17.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_11.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_18.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_19.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_14.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_15.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_7.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_25.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_28.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_29.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_16.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_13.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_24.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_21.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_20.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_1.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_3.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_10.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_9.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_27.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_26.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_4.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_0.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_12.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_6.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_23.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_5.csv
MO_metadata_soupxplus5_cleaned_03122025_subclass_250_2.csv

In [89]:
fin = []
for item in mode_df.columns:
    fin.append(mode_df.loc[10000,item])

In [90]:
scipy.stats.mode(fin)

ModeResult(mode=array([62]), count=array([30]))

In [91]:
import re

mn = sorted(mn, key=lambda s: [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', s)])

In [92]:
mn

['MO_metadata_soupxplus5_cleaned_03122025_subclass_250_0.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_1.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_2.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_3.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_4.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_5.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_6.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_7.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_8.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_9.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_10.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_11.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_12.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_13.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_14.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_15.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_16.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_17.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_18.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_19.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_20.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_21.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_22.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_23.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_24.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_25.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_26.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_27.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_28.csv',
 'MO_metadata_soupxplus5_cleaned_03122025_subclass_250_29.csv']

In [93]:
lsamap_mv = pd.DataFrame(index = [a for a in barcodes], columns = [b for b in range(len(mn))])
for j in range(len(mn)):
    dat = list(pd.read_csv(meta_folder + mn[j])['subclass_id_label_mapping'])
    lsamap_mv.loc[:,j] = dat

In [94]:
lsamap_m = lsamap_mv

In [ ]:
#for vole
threshold = .75
mapping_dict ={}
a = 0
b = 0
for lc in sam.adata.obs['eq_subclass_lc'].unique():
    a += 1
    inp = ['Unlabeled', 'Unlabeled']
    barcodes = sam.adata.obs_names[sam.adata.obs['eq_subclass_lc'] == lc]
    ct_saturn_m = lsaturn_m[lsaturn_m.index.isin(barcodes)].values.ravel()
    ct_samap_m = lsamap_m[lsamap_m.index.isin(barcodes)].values.ravel()
    
    mode_saturn_m,f_saturn_m = scipy.stats.mode(ct_saturn_m)
    mode_samap_m,f_samap_m = scipy.stats.mode(ct_samap_m)
    if  f_saturn_m[0]/len(ct_saturn_m)>= threshold:
        inp[0] = mode_saturn_m[0]
    if f_samap_m[0]/len(ct_samap_m) >= threshold:
        inp[1] = mode_samap_m[0]
    if inp[1] != inp[0] and inp[0] != 'Unlabeled' and inp[1] != 'Unlabeled':
        b += len(sam.adata.obs_names[sam.adata.obs['eq_subclass_lc'] == lc])
        if inp[0] == '077 CEA-BST Gal Avp Gaba':
            mapping_dict[lc] = 'mg_077_106'
        elif inp[0] == '105 TMd-DMH Foxd2 Gaba':
            mapping_dict[lc] = 'mg_105_107'
        print(inp[0],inp[1])
    inp_val = list(set(inp) - set(['Unlabeled']))
    if len(inp_val) == 0:
        mapping_dict[lc] = 'Unlabeled'
    elif len(inp_val) == 1:
        mapping_dict[lc] = inp_val[0]

In [96]:
new_mapping = []
new_mapping_name = 'test'
for item in sam.adata.obs['eq_subclass_lc']:
    new_mapping.append(mapping_dict[item])
sam.adata.obs[new_mapping_name] = new_mapping

In [76]:
np.sort(sam.adata.obs['ss_subclass'].unique())

array(['007 L2/3 IT CTX Glut', '009 L2/3 IT PIR-ENTl Glut',
       '010 IT AON-TT-DP Glut', '014 LA-BLA-BMA-PA Glut',
       '016 CA1-ProS Glut', '017 CA3 Glut', '022 L5 ET CTX Glut',
       '037 DG Glut', '041 OB-in Frmd7 Gaba', '047 Sncg Gaba',
       '049 Lamp5 Gaba', '054 STR Prox1 Lhx6 Gaba', '055 STR Lhx8 Gaba',
       '056 Sst Chodl Gaba', '057 NDB-SI-MA-STRv Lhx8 Gaba',
       '058 PAL-STR Gaba-Chol', '059 GPe-SI Sox6 Cyp26b1 Gaba',
       '061 STR D1 Gaba', '062 STR D2 Gaba', '063 STR D1 Sema5a Gaba',
       '064 STR-PAL Chst9 Gaba', '066 NDB-SI-ant Prdm12 Gaba',
       '067 LSX Sall3 Pax6 Gaba', '068 LSX Otx2 Gaba',
       '069 LSX Nkx2-1 Gaba', '070 LSX Prdm12 Slit2 Gaba',
       '073 MEA-BST Sox6 Gaba', '074 MEA-BST Lhx6 Sp9 Gaba',
       '075 MEA-BST Lhx6 Nr2e1 Gaba', '076 MEA-BST Lhx6 Nfib Gaba',
       '077 CEA-BST Gal Avp Gaba', '078 SI-MA-ACB Ebf1 Bnc2 Gaba',
       '079 CEA-BST Six3 Cyp26b1 Gaba', '080 CEA-AAA-BST Six3 Sp9 Gaba',
       '081 ACB-BST-FS D1 Gaba', '082 CEA-BST Ebf1 Pdyn Gaba',
       '083 CEA-BST Rai14 Pdyn Crh Gaba',
       '084 BST-SI-AAA Six3 Slc22a3 Gaba', '085 SI-MPO-LPO Lhx8 Gaba',
       '086 MPO-ADP Lhx8 Gaba', '087 MPN-MPO-LPO Lhx6 Zfhx3 Gaba',
       '088 BST Tac2 Gaba', '089 PVR Six3 Sox3 Gaba',
       '090 BST-MPN Six3 Nrgn Gaba', '091 ARH-PVi Six6 Dopa-Gaba',
       '092 TMv-PMv Tbx3 Hist-Gaba', '093 RT-ZI Gnb3 Gaba',
       '094 SCH Six6 Cdc14a Gaba', '097 PVHd-SBPV Six3 Prox1 Gaba',
       '098 AHN-SBPV-PVHd Pdrm12 Gaba', '099 SBPV-PVa Six6 Satb2 Gaba',
       '100 AHN Onecut3 Gaba', '101 ZI Pax6 Gaba',
       '102 DMH-LHA Gsx1 Gaba', '103 PVHd-DMH Lhx6 Gaba',
       '104 TU-ARH Otp Six6 Gaba', '105 TMd-DMH Foxd2 Gaba',
       '106 PVpo-VMPO-MPN Hmx2 Gaba', '107 DMH Hmx2 Gaba',
       '108 ARH-PVp Tbx3 Gaba', '111 TRS-BAC Sln Glut',
       '112 GPi Tbr1 Cngb3 Gaba-Glut', '113 MEA-COA-BMA Ccdc42 Glut',
       '114 COAa-PAA-MEA Barhl2 Glut', '115 MS-SF Bsx Glut',
       '116 AVPV-MEPO-SFO Tbr1 Glut', '117 LHA Barhl2 Glut',
       '118 ADP-MPO Trp73 Glut', '119 SI-MA-LPO-LHA Skor1 Glut',
       '120 MEA Otp Foxp2 Glut', '121 MEA-BST Otp Zic2 Glut',
       '122 LHA-MEA Otp Glut', '123 DMH Nkx2-4 Glut',
       '124 MPN-MPO-PVpo Hmx2 Glut', '125 DMH Hmx2 Glut',
       '126 ARH-PVp Tbx3 Glut', '127 DMH-LHA Vgll2 Glut',
       '128 VMH Fezf1 Glut', '129 VMH Nr5a1 Glut', '130 LHA Pmch Glut',
       '131 LHA-AHN-PVH Otp Trh Glut', '132 AHN-RCH-LHA Otp Fezf1 Glut',
       '133 PVH-SO-PVa Otp Glut', '134 PH-ant-LHA Otp Bsx Glut',
       '135 STN-PSTN Pitx2 Glut', '136 PMv-TMv Pitx2 Glut',
       '137 PH-an Pitx2 Glut', '138 PH Pitx2 Glut',
       '139 PH-LHA Foxb1 Glut', '140 PMd-LHA Foxb1 Glut',
       '141 PH-SUM Foxa1 Glut', '143 MM-ant Foxb1 Glut',
       '144 MM Foxb1 Glut', '149 PVT-PT Ntrk1 Glut',
       '151 TH Prkcd Grin2c Glut', '152 RE-Xi Nox4 Glut',
       '159 IF-RL-CLI-PAG Foxa1 Glut',
       '168 SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut', '184 PAG Tcf24 Glut',
       '195 SNr-VTA Pax5 Npas1 Gaba', '196 PAG-PPN Pax5 Sox21 Gaba',
       '197 SNr Six3 Gaba', '200 PAG-ND-PCG Onecut1 Gaba',
       '214 IPN Otp Crisp1 Gaba', '215 SNc-VTA-RAmb Foxa1 Dopa',
       '230 PRNr Otp Nfib Glut', '231 IPN-LDT Vsx2 Nkx6-1 Glut',
       '235 PG-TRN-LRN Fat2 Glut', '257 SPVC Ccdc172 Glut',
       '268 CS-PRNr-DR En1 Sox2 Gaba', '277 DTN-LDT-IPN Otp Pax3 Gaba',
       '322 Tanycyte NN', '326 OPC NN', '327 Oligo NN',
       '334 Microglia NN', 'Unlabeled', 'mg_077_106', 'mg_105_107'],
      dtype=object)

In [29]:
a = 0
for item in sam.adata.obs_names:
    if df.loc[item,'fin_ct'] == sam.adata.obs.loc[item,'test']:
        print(df.loc[item,'fin_ct'],sam.adata.obs.loc[item,'test'])
        a += 1

Unlabeled Unlabeled

In [28]:
a

75330

In [27]:
sam.adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,n_counts,n_genes,key,subclass_id_label_mapping,subclass_id_label_lc,leiden_clusters,subclass_id_label_mapping_nounlabeled,...,NN,ss_subclass,ss_subclass_nounlabeled,ss_subclass_nounlabeled_03102026,ss_subclass_nounlabeled_03102026_crossed,neurotransmitter_v2,test,ss_subclass_threshold_90,yanay_labels,yanay_label_nounlabeled
AAACCCATCTCAAAGC,MO,11772.0,3844,11772.0,3844,Run12_sample1,Unlabeled,131,32,mo_15,...,Unlabeled,Unlabeled,mo_18,mo_5,107 DMH Hmx2 Gaba,Gaba,Unlabeled,Unlabeled,Unlabeled,mo_28
AAACGAACAGCACGAA,MO,4877.0,2561,4877.0,2561,Run12_sample1,Unlabeled,290,24,mo_10,...,Unlabeled,Unlabeled,mo_6,mo_0,124 MPN-MPO-PVpo Hmx2 Glut,Glut,Unlabeled,Unlabeled,Unlabeled,mo_8
AAACGAAGTCGGCACT,MO,5221.0,2859,5221.0,2859,Run12_sample1,108 ARH-PVp Tbx3 Gaba,27,12,108 ARH-PVp Tbx3 Gaba,...,Neuron,108 ARH-PVp Tbx3 Gaba,108 ARH-PVp Tbx3 Gaba,108 ARH-PVp Tbx3 Gaba,108 ARH-PVp Tbx3 Gaba,Gaba,108 ARH-PVp Tbx3 Gaba,108 ARH-PVp Tbx3 Gaba,108 ARH-PVp Tbx3 Gaba,108 ARH-PVp Tbx3 Gaba
AAACGAATCCACCCTA,MO,7922.0,3360,7922.0,3360,Run12_sample1,Unlabeled,529,85,mo_9,...,Unlabeled,Unlabeled,mo_38,mo_23,133 PVH-SO-PVa Otp Glut,Glut,Unlabeled,Unlabeled,Unlabeled,mo_47
AAACGAATCCCAGCGA,MO,7020.0,3204,7020.0,3204,Run12_sample1,128 VMH Fezf1 Glut,104,31,128 VMH Fezf1 Glut,...,Neuron,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGGTACTAACC,MO,5496.0,2569,5496.0,2569,Run12_sample12,057 NDB-SI-MA-STRv Lhx8 Gaba,217,5,057 NDB-SI-MA-STRv Lhx8 Gaba,...,Neuron,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba
TTTGTTGGTCACAATC-1,MO,2974.0,1804,2974.0,1804,Run12_sample12,089 PVR Six3 Sox3 Gaba,204,13,089 PVR Six3 Sox3 Gaba,...,Neuron,089 PVR Six3 Sox3 Gaba,089 PVR Six3 Sox3 Gaba,089 PVR Six3 Sox3 Gaba,089 PVR Six3 Sox3 Gaba,Gaba,089 PVR Six3 Sox3 Gaba,089 PVR Six3 Sox3 Gaba,089 PVR Six3 Sox3 Gaba,089 PVR Six3 Sox3 Gaba
TTTGTTGTCCAACCAA,MO,5601.0,2608,5601.0,2608,Run12_sample12,Unlabeled,211,13,mo_11,...,Unlabeled,Unlabeled,mo_4,mo_5,107 DMH Hmx2 Gaba,Gaba,Unlabeled,Unlabeled,Unlabeled,mo_7
TTTGTTGTCCCTGTTG,MO,6209.0,2759,6209.0,2759,Run12_sample12,Unlabeled,478,8,mo_4,...,Unlabeled,Unlabeled,mo_7,mo_1,mo_1,Glut,Unlabeled,Unlabeled,Unlabeled,mo_11
TTTGTTGTCGCAGTTA,MO,5151.0,2617,5151.0,2617,Run12_sample12,086 MPO-ADP Lhx8 Gaba,91,22,086 MPO-ADP Lhx8 Gaba,...,Neuron,086 MPO-ADP Lhx8 Gaba,086 MPO-ADP Lhx8 Gaba,086 MPO-ADP Lhx8 Gaba,086 MPO-ADP Lhx8 Gaba,Gaba,086 MPO-ADP Lhx8 Gaba,086 MPO-ADP Lhx8 Gaba,086 MPO-ADP Lhx8 Gaba,086 MPO-ADP Lhx8 Gaba

In [100]:
a = 0
fin_obs = []
for item in sam.adata.obs_names:
    if sam.adata.obs.loc[item,'test'] == sam.adata.obs.loc[item,'ss_subclass']:
        a += 1
        fin_obs.append(item)

In [101]:
a

75330

In [102]:
len(sam.adata)

75330

In [58]:
sam.save_anndata(fn)