In [3]:
!pip install plotly

Collecting plotly
  Downloading plotly-5.18.0-py3-none-any.whl (15.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 24.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: packaging in /scratch/miniconda/lib/python3.7/site-packages (from plotly) (21.3)
Collecting tenacity>=6.2.0
  Downloading tenacity-8.2.3-py3-none-any.whl (24 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /scratch/miniconda/lib/python3.7/site-packages (from packaging->plotly) (3.0.9)
Installing collected packages: tenacity, plotly
Successfully installed plotly-5.18.0 tenacity-8.2.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [4]:
!pip install "anywidget>=0.9.13"

Collecting anywidget>=0.9.13
  Downloading anywidget-0.9.13-py3-none-any.whl (213 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.7/213.7 kB 2.6 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: typing-extensions>=4.2.0 in /scratch/miniconda/lib/python3.7/site-packages (from anywidget>=0.9.13) (4.2.0)
Collecting psygnal>=0.8.1
  Downloading psygnal-0.9.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (477 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 477.3/477.3 kB 7.1 MB/s eta 0:00:0000:01
Requirement already satisfied: importlib-metadata in /scratch/miniconda/lib/python3.7/site-packages (from anywidget>=0.9.13) (4.11.4)
Collecting ipywidgets>=7.6.0
  Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.8/139.8 kB 2.3 MB/s eta 0:00:00a 0:00:01
Collecting jupyterlab_widgets~=3.0.15
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 914.9/914.9 kB 11.8 MB/s eta 0:00:0000:01
Collecting widgetsnbextension~=4.0.14
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 22.6 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: traitlets>=4.3.1 in /scratch/miniconda/lib/python3.7/site-packages (from ipywidgets>=7.6.0->anywidget>=0.9.13) (5.3.0)
Requirement already satisfied: ipython>=6.1.0 in /scratch/miniconda/lib/python3.7/site-packages (from ipywidgets>=7.6.0->anywidget>=0.9.13) (7.33.0)
Collecting comm>=0.1.3
  Downloading comm-0.1.4-py3-none-any.whl (6.6 kB)
Collecting mypy-extensions
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: zipp>=0.5 in /scratch/miniconda/lib/python3.7/site-packages (from importlib-metadata->anywidget>=0.9.13) (3.8.0)
Requirement already satisfied: pickleshare in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (0.7.5)
Requirement already satisfied: backcall in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (0.2.0)
Requirement already satisfied: decorator in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (5.1.1)
Requirement already satisfied: pygments in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (2.12.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (3.0.30)
Requirement already satisfied: pexpect>4.3 in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (4.8.0)
Requirement already satisfied: setuptools>=18.5 in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (62.6.0)
Requirement already satisfied: matplotlib-inline in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (0.1.3)
Requirement already satisfied: jedi>=0.16 in /scratch/miniconda/lib/python3.7/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (0.18.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /scratch/miniconda/lib/python3.7/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /scratch/miniconda/lib/python3.7/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (0.7.0)
Requirement already satisfied: wcwidth in /scratch/miniconda/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget>=0.9.13) (0.2.5)
Installing collected packages: widgetsnbextension, mypy-extensions, jupyterlab_widgets, comm, psygnal, ipywidgets, anywidget
Successfully installed anywidget-0.9.13 comm-0.1.4 ipywidgets-8.1.8 jupyterlab_widgets-3.0.16 mypy-extensions-1.0.0 psygnal-0.9.5 widgetsnbextension-4.0.15
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [5]:
!pip install -U kaleido

Requirement already satisfied: kaleido in /scratch/miniconda/lib/python3.7/site-packages (0.2.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [1]:
from samap.mapping import SAMAP
from samap.analysis import (get_mapping_scores, GenePairFinder, transfer_annotations,
                            sankey_plot, chord_plot, CellTypeTriangles, 
                            ParalogSubstitutions, FunctionalEnrichment,
                            convert_eggnog_to_homologs, GeneTriangles)
from samalg import SAM
import pandas as pd
from Bio import SeqIO
from samap.utils import (save_samap, load_samap)
import scanpy as sc
import matplotlib.colors
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from scipy import sparse 
from scipy import cluster
import seaborn as sns
import random
import sklearn
from scipy.stats import poisson
from sklearn.neighbors import KernelDensity
import time
import dill
from scipy.optimize import minimize
import pickle
import itertools
import os
import plotly.express as px

In [2]:
df_NN = pd.DataFrame(columns = ['org','celltype','mapping','frac cells'])

In [3]:
a = 0

In [4]:
sm = load_samap('Active_SAMap_Joined/sm_nonneural_hypothalamus_06082026.pk')

In [36]:
org = 'cj'
ref = 'mg'

In [37]:
for item in sm.sams[org].adata.obs['ss_subclass_nounlabeled_nmm_v3_nn'].unique():
    print(item)

327 Oligo NN
326 OPC NN
319 Astro-TE NN
318 Astro-NT NN
339 astrocyte-like NN
341 macrophages NN
Unlabeled
323 Ependymal NN
322 Tanycyte NN
330 VLMC NN
329 ABC NN
325 CHOR NN
340 vascular cells NN
333 Endo NN

In [38]:
mappings = {'317 Astro-CB NN':'Astrocytes',
'318 Astro-NT NN':'Astrocytes',
'319 Astro-TE NN':'Astrocytes',
'320 Astro-OLF NN':'Astrocytes',
'321 Astroependymal NN':'Astrocytes',
'339 astrocyte-like NN':'Astrocytes',
'334 Microglia NN':'Macrophage',
'335 BAM NN':'Macrophage',
'341 macrophages NN':'Macrophage'}

In [39]:
fin_org = []
for item in sm.sams[org].adata.obs['ss_subclass_nounlabeled_nmm_v3_nn']:
    if item in mappings:
        fin_org.append(mappings[item])
    else:
        fin_org.append(item)
        
fin_ref = []
for item in sm.sams[ref].adata.obs['subclass_id_label']:
    if item in mappings:
        fin_ref.append(mappings[item])
    else:
        fin_ref.append(item)

In [40]:
sm.sams[ref].adata.obs['figure2e_mapping'] = fin_ref
sm.sams[org].adata.obs['figure2e_mapping'] = fin_org

In [41]:
ref_level = 'figure2e_mapping'
org_level = 'figure2e_mapping'

In [42]:
keys = {ref:ref_level,org:org_level}
D,MappingTable = get_mapping_scores(sm,keys)

lim_MappingTable = MappingTable.filter(like=org)
lim_MappingTable = lim_MappingTable[lim_MappingTable.index.str.contains(ref)]

/scratch/miniconda/lib/python3.7/site-packages/samap/analysis.py:1609: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  samap.adata.obs[l] = pd.Categorical(cl)

In [43]:
sam = SAM()
sam.load_data('Active_SAM_joined/SAM_CJ_joined_v2_cleaned_03122025.h5ad')

In [44]:
for item in sm.sams[ref].adata.obs[ref_level].unique():
    print(org + '_' + item)
    if org + '_' + item in lim_MappingTable.columns:
        df_NN.loc[a, 'mapping'] = lim_MappingTable.loc[ref + '_' + item, org + '_' + item]
        df_NN.loc[a, 'org'] = org
        df_NN.loc[a, 'celltype'] = item
        df_NN.loc[a, 'num cells'] = len(sm.sams[org].adata[sm.sams[org].adata.obs[org_level] == item])
        df_NN.loc[a, 'frac cells'] = len(sm.sams[org].adata[sm.sams[org].adata.obs[org_level] == item])/len(sam.adata)
        a += 1

cj_Astrocytes
cj_322 Tanycyte NN
cj_316 Bergmann NN
cj_325 CHOR NN
cj_330 VLMC NN
cj_323 Ependymal NN
cj_324 Hypendymal NN
cj_326 OPC NN
cj_327 Oligo NN
cj_329 ABC NN
cj_328 OEC NN
cj_331 Peri NN
cj_332 SMC NN
cj_333 Endo NN
cj_338 Lymphoid NN
cj_Macrophage
cj_337 DC NN
cj_336 Monocytes NN

In [45]:
df_NN

   org          celltype   mapping frac cells  num cells
0   dr        Astrocytes  0.455964   0.029319     2424.0
1   dr   322 Tanycyte NN  0.233479   0.001318      109.0
2   dr   316 Bergmann NN  0.324959   0.004971      411.0
3   dr       330 VLMC NN  0.824805   0.005491      454.0
4   dr  323 Ependymal NN  0.778237   0.010499      868.0
5   dr        326 OPC NN  0.844728    0.01859     1537.0
6   dr      327 Oligo NN  0.783695   0.008055      666.0
7   dr        329 ABC NN  0.743983   0.002552      211.0
8   dr        328 OEC NN    0.3341   0.007511      621.0
9   dr       331 Peri NN  0.752488   0.001838      152.0
10  dr        332 SMC NN  0.634467    0.00462      382.0
11  dr       333 Endo NN  0.895139   0.014623     1209.0
12  dr        Macrophage  0.850309   0.010934      904.0
13  dr         337 DC NN  0.476303   0.001657      137.0
14  dr  336 Monocytes NN  0.237138   0.000327       27.0
15  xt        Astrocytes  0.704065    0.01215      513.0
16  xt   322 Tanycyte NN  0.464935   0.003126      132.0
17  xt       330 VLMC NN   0.77491    0.00244      103.0
18  xt        326 OPC NN  0.838847   0.020369      860.0
19  xt      327 Oligo NN  0.775173   0.010374      438.0
20  xt        329 ABC NN  0.701888   0.000758       32.0
21  xt       333 Endo NN  0.953791   0.001516       64.0
22  xt        Macrophage  0.934988   0.001729       73.0
23  ac        Astrocytes  0.816076   0.038476     1843.0
24  ac   322 Tanycyte NN  0.448155   0.004823      231.0
25  ac       330 VLMC NN  0.942809   0.011712      561.0
26  ac        326 OPC NN  0.891318   0.027891     1336.0
27  ac      327 Oligo NN  0.774184   0.124071     5943.0
28  ac        329 ABC NN  0.936981   0.000585       28.0
29  ac       333 Endo NN   0.94295   0.002443      117.0
30  ac   338 Lymphoid NN  0.685852   0.001086       52.0
31  ac        Macrophage  0.902701   0.018163      870.0
32  cj        Astrocytes  0.785548   0.071537     5348.0
33  cj   322 Tanycyte NN  0.652785   0.004802      359.0
34  cj       325 CHOR NN  0.859959   0.000375       28.0
35  cj       330 VLMC NN  0.925259   0.006019      450.0
36  cj  323 Ependymal NN  0.903718   0.003264      244.0
37  cj        326 OPC NN  0.926144    0.03114     2328.0
38  cj      327 Oligo NN  0.820691   0.123933     9265.0
39  cj        329 ABC NN  0.922134   0.001899      142.0
40  cj       333 Endo NN  0.981145   0.000522       39.0
41  cj        Macrophage  0.882527    0.00309      231.0

In [46]:
ct_int = ['327 Oligo NN','326 OPC NN','322 Tanycyte NN','Astrocytes','Macrophage']

In [47]:
df_NN = df_NN[df_NN['celltype'].isin(ct_int)]

In [48]:
df_NN['frac cells'] = df_NN['frac cells'].clip(upper=.1)

/scratch/miniconda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [49]:
df_NN['frac cells'] = df_NN['frac cells'].astype('float')
df_NN['mapping'] = df_NN['mapping'].astype('float')

/scratch/miniconda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/scratch/miniconda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [50]:
['322 Tanycyte NN','Astrocytes','Macrophage','326 OPC NN','327 Oligo NN']

['322 Tanycyte NN', 'Astrocytes', 'Macrophage', '326 OPC NN', '327 Oligo NN']

In [51]:
fig = px.scatter(df_NN, x = 'org', y = 'celltype', size = 'frac cells', color = 'mapping', color_continuous_scale= 'Blues', range_color=[0,.99],opacity = 1)
fig.update_xaxes(categoryorder='array', categoryarray= ['cj','ac','xt','dr'])
fig.update_yaxes(categoryorder='array', categoryarray= ['322 Tanycyte NN','Astrocytes','Macrophage','326 OPC NN','327 Oligo NN'])
fig.update_layout(
    autosize=False,
    width=400,
    height=300,
)

fig.write_image("Figures/Figures_06082026/NN_mapping_allorgs_epen_06082026.png")
fig.write_image("Figures/Figures_06082026/NN_mapping_allorgs_epen_06082026.svg")

In [75]:
df_NN

   org          celltype   mapping  frac cells
0   ac   322 Tanycyte NN  0.826871    0.007829
1   ac   319 Astro-TE NN  0.888687    0.023215
2   ac        326 OPC NN  0.948104    0.024113
3   ac      327 Oligo NN  0.952918    0.100000
9   ac  334 Microglia NN  0.802459    0.010898
10  cj   322 Tanycyte NN  0.663972    0.007477
11  cj   319 Astro-TE NN  0.369639    0.006233
15  cj        326 OPC NN  0.969029    0.030659
16  cj      327 Oligo NN  0.877350    0.100000
21  cj  334 Microglia NN  0.866150    0.003545
22  xt   322 Tanycyte NN  0.885898    0.017669
23  xt        326 OPC NN  0.857654    0.020677
24  xt      327 Oligo NN  0.923299    0.013098
27  dr   322 Tanycyte NN  0.186175    0.011382
29  dr        326 OPC NN  0.975893    0.013196
30  dr      327 Oligo NN  0.851781    0.008600